version: '3'
services:
  redis-docker:
    image: redis:latest
    container_name: 'redis-lab'
    command: redis-server --port 6379
    ports:
      - '6379:6379'
    volumes:
      - /Users/leeeeeyeon/data/db-docker/data/redis:/data
